---
all:
  children:
    cisco:
      hosts:
        csr-test:
          ansible_host: 10.30.10.31
    firewall:
      children:
        asa:
          vars:
            ansible_network_os: asa
          hosts:
            ASA-FW1:
              ansible_host: 10.10.10.1
