---
all:
  children:
    router:
      children:
        iosxe:
          children:
            edge:
              hosts:
                dc1-csr-xnet1:
                  ansible_host: 10.10.108.17
    switch:
      children:
        nxos:
          children:
            spine:
              hosts:
                dc1-n9k-spine1:
                  ansible_host: 10.10.108.11
                dc1-n9k-spine2:
                  ansible_host: 10.10.108.12
            leaf:
              hosts:
                dc1-n9k-leaf1:
                  ansible_host: 10.10.108.13
                dc1-n9k-leaf2:
                  ansible_host: 10.10.108.14
            border_leaf:
              hosts:
                dc1-n9k-border1:
                  ansible_host: 10.10.108.15
        ios:
          children:
            dmz:
              hosts:
                dc1-vios-sw1:
                  ansible_host: 10.10.108.18
    firewall:
      children:
        asa:
          hosts:
            dc1-asav-xfw1:
              ansible_host: 10.10.108.16
    bigip:
      children:
        ltm:
          hosts:
            dc1-ltm-lb1:
              ansible_host: 10.10.108.19
