---
git_repo: git@github.com:sjhloco/ip_auto_lab.git
repo_path: /tmp/ip_auto_lab
ansible_python_interpreter: "/usr/bin/python3.7" 

creds_all:
  hostname: "{{ ansible_host|default(inventory_hostname) }}"
  username: admin
  password: ansible