---
# This playbook backs up the device configurations to a remote git repo
- name: "Creating file structure"
  hosts: localhost
  tasks:
    # Create a date fact (variable) to be used in the GIT message
    - name: SYS >> Get ansible date/time facts
      setup:
        filter: "ansible_date_time"
    - name: SYS >> Store Date in a Fact
      set_fact:
        DATE: "{{ ansible_facts.date_time.date }}"
    # Clone a remote repo to save the config output in
    - name: GIT >> Clone private repo into /tmp
      git:
        repo: "{{ git_repo }}"
        version: master
        dest: "{{ repo_path }}"
        single_branch: true # Clone just one branch
        depth: 1

# Create copy of Cisco running configs
- name: "Backing up Devices with NAPALM"
  hosts: router:switch:firewall
  tasks:
    - name: "NET >> Backup Cisco running configs"
      napalm.napalm.napalm_get_facts:
        filter:
          - "config"
      tags: [print_action]
    # Save the configs to file in /tmp
    - name: SYS >> Save output to backup dir
      copy:
        content: "{{ ansible_facts.napalm_config.running }}" # nested ansible fact
        dest: "{{ repo_path }}/backup_configs/configs/{{ inventory_hostname }}.cfg"
      delegate_to: localhost

# Create a F5 UCS backup - not tested on recent ansible code
# - name: Backup BIGIP Devices with BIGIP module
#   hosts: bigip
#   tasks:
#   - name: Create and download a UCS
#     bigip_ucs_fetch:
#       src: "{{ inventory_hostname }}.ucs"
#       dest: "{{ repo_path }}/configurations/{{ inventory_hostname }}.ucs"
#       provider: "{{ creds_big_ip }}"
#       backup: yes                 # Will backup if doesnt already exist
#     delegate_to: localhost
#     tags: [print_action]

# Commit and push changes to it and cleanup file directory
- name: Push config backups to git and cleanup
  hosts: localhost
  tasks:
    # First check if anything has changed
    - name: GIT >> Check for changes
      ansible.builtin.command:
        cmd: git status --porcelain
        chdir: "{{ repo_path }}"
      register: git_status
      changed_when: false # So play doesn't never marks task as changed
    # If changed then commit and push changes to the repo
    - name: GIT >> Commit and push backups
      when: git_status.stdout | length > 0
      block:
        - name: GIT >> Stage changes
          ansible.builtin.command:
            cmd: git add --all
            chdir: "{{ repo_path }}"
        - name: GIT >> Commit
          ansible.builtin.command:
            cmd: git commit -m "Config backups by Ansible {{ hostvars.localhost.DATE }}"
            chdir: "{{ repo_path }}"
          environment:
            GIT_AUTHOR_NAME: Ansible
            GIT_AUTHOR_EMAIL: ansible@lab.local
            GIT_COMMITTER_NAME: Ansible
            GIT_COMMITTER_EMAIL: ansible@lab.local
        - name: GIT >> Push
          ansible.builtin.command:
            cmd: git push origin HEAD
            chdir: "{{ repo_path }}"

    # Cleanup the directory
    - name: "SYS >> Delete the directory"
      file:
        path: "{{ repo_path }}"
        state: absent
