---
# This playbook backs up the device configurations to a remote git repo

- name: "xxx"
- hosts: all
  vars:
    configs: configs

  pre_tasks:
    - file: path={{configs}} state=directory

  roles:
    - ospf_router					 

  post_tasks:
    - assemble:
      src: "{{configs}}"
      dest: "configs/{{inventory_hostname}}.cfg"