# need to install this on the ansibel host first pip install PyVmomi
- name: "VMware vDS and vLS deployments"
  hosts: localhost

  vars_files:
    - vars/ansible.yml
    - vars/port_groups.yml

  tasks:
    - name: Create vDS vlan portgroup
      connection: local
      vmware_dvs_portgroup:
        hostname: "{{ login.vcenter }}"
        username: "{{ login.user }}"
        password: "{{ login.pass }}"
        validate_certs: false
        switch_name: "{{ item.0.name }}"
        portgroup_name: "{{ item.1.name }}"
        vlan_id: "{{ item.1.vlan_nr }}"
        num_ports: "{{ item.1.num_ports }}"
        portgroup_type: earlyBinding
        state: "{{ item.1.state }}"
        teaming_policy:
          # Cant set the LDAP active and standy ports, that has to be done manually in vCentre
          load_balance_policy: loadbalance_ip
      loop: "{{ vds | subelements('port_grp') }}"
      tags: vds

    - name: Create vLS vlan portgroup
      vmware_portgroup:
        hostname: "{{ login.vcenter }}"
        username: "{{ login.user }}"
        password: "{{ login.pass }}"
        validate_certs: false
        esxi_hostname: "{{ item.0.esx_host }}"
        switch_name: "{{ item.0.name }}"
        portgroup_name: "{{ item.1.name }}"
        vlan_id: "{{ item.1.vlan_nr }}"
        state: "{{ item.1.state }}"
      loop: "{{ vls | subelements('port_grp') }}"
      tags: vls