---
# Saves all Ansible variables/facts, one file for each command

# Creates an empty file structure by first deleting then creating directories
- name: "SYS >> Create the file structure"
  hosts: localhost
  tasks:
    - ansible.builtin.file: path="/tmp/results" state=absent # noqa: name[missing] no-free-form
    - ansible.builtin.file: path="/tmp/results" state=directory # noqa: name[missing] no-free-form risky-file-permissions

# Runs show cmds using list of cmds from group_vars
- name: Run commands
  hosts: router # Runs on all hosts in cisco or asa group
  tasks:
    - name: "NET >> Run device show cmds"
      ansible.netcommon.cli_command:
        command: "{{ item }}"
      loop: "{{ commands }}"
      register: cli_output

    # Saves all variables per host in own file
    - name: "NET >> Save Host Outputs"
      ansible.builtin.copy: # noqa: risky-file-permissions
        # Copies the each output as specified by the loop element index number got from the loop
        content: "{{ cli_output.results[cmd_num].stdout }}"
        # Creates file_name using cmd list replacing all spaces
        dest: "/tmp/results/{{ inventory_hostname }}_{{ item | replace(' ', '-') }}.cfg"
      loop: "{{ commands }}" # Loops through list of cmds
      loop_control:
        index_var: cmd_num #  Creates index number for each iteration
      delegate_to: localhost
